server:
  port: 8086

spring:
  application:
    name: resena
  datasource:
    url: jdbc:mysql://localhost:3306/nubos_resena?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Santiago
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
