spring.application.name=carrito

server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/nubos_carrito?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true