spring.application.name=promocion

server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/nubos_promocion?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true